### ISSUE TITLE
Add a push functionality on enhancements page for activated skills

### ISSUE THREAD

**Issue by Wisdomb33r** [Wisdomb33r/ffch-admin#264]
If an skill which activates other skills have enhancements (Brave, Latent or Regular) and the activated skill changes accordingly, the page to push enhancements should offer a functionality (for instance a second list of skills under the enhancements themselves) to push these transitive enhancements too.

**Comment by Sylvie** [comment]
### Tasks

- [ ] Add the models to store innate and activated Enhancements
- [ ] Add the model to store innate and activated Ameliorations
- [ ] Add the possibility to map one model into the other
- [ ] Display the activated Améliorations as well
- [ ] Do something smart (or not) to compute the enhancements activated by a given enhancement
- [ ] Since we are at it: fix the "Amélioration" checkbox that cannot be unchecked for skills

**Comment by Sylvie** [comment]
### Perso à problèmes

- Prishe (amélioration de compétences de type "switch" qui donnent accès à des compétences...)
- Elena (compétences de type "stance" qui s'activent l'une l'autre)
- Sacred Shield Charlotte (fait sauter la baraque)
- Nameless Gunner Jake (active un skill en plus au niveau 2)
